---
title: "Actividad 6: Datos espaciales"
lang: "es_CL"
description: "Utilizar QGIS, R y SQL para manejar datos espaciales."
output:
  distill::distill_article:
    toc: true
    toc_float: true
    pandoc_args: ["--number-sections"]
---


# Ejercicio 1: conectar QGIS a postgis

Conectar Qgis a la base de datos puerto_wilches.
Utilizar un fondo de mapa (google) para representar los eventos de muestreo del proyecto sobre una imagen satelital.

Poner colores a los puntos de evento en función de los grupos biológicos (utilizar comandos SQL/postgis con el DBManager de QGIS).

# Ejercicio 2: buscar correspondencia con comunas en Chile

El archivo DarwinCore que descargamos en GBIF en el taller 2 no contiene la información de las comunas.
El archivo "comunas.zip" contiene los poligonos de  las comunas chilenas.

# Ejercicio 3: Calcular sesgos de ecosistemas en el muestreo de escarabajos

En Puerto Wilches, queremos ver si el muestreo de escarabajos tuvo un sesgo de habitat.

La idea acá es crear una base de datos postgis para almacenar datos espaciales que corresponden a las localizaciones de escarabajos.
Los archivos necesarios son:

* landcov.shp contiene los habitat en el municipio de Puerto Wilches
* esca_event.csv contiene los eventos de muestreo de escarabajos

1. Crear una base de datos postgis vacía desde qgis
1. Leer los archivos en R para enviarlos en la base de datos, como capas espaciales
1. Calcular las superficies de ecosistemas utilizando postgis
1. Calcular el numero de eventos en cada habitar utilizando postgis
1. ¡Comparar!