---
title: "Instalar software para SQL"
description: "Instalación de software para el curso Biodata: Bases de datos SQL"
output:
  distill::distill_article:
    toc: true
    toc_float: true
    pandoc_args: ["--number-sections"]
bibliography: "./biodata2024.bib"
---

La instalación descrita acá es una instalación de 2 sistemas opensource de gestión de bases de datos relacionales: `PostgreSQL` (<https://www.postgresql.org/>) y `SQLite`(<https://www.sqlite.org/>).

`PostgreSQL` es un motor de bases de datos que funciona con un modelo clásico servidor/cliente.
Es decir que los software que permiten hacer consultas en una base de datos están instalados en el cliente, y se pueden conectar a los servidores para enviar las comandas de consulta.
Cuando creamos una base de datos local, el sistema considera que se conecta a un servidor "localhost" que corresponde al computador local.
Por esa razón es importante instalar ambas partes "cliente" y "servidor" para poder trabajar con bases de datos locales y accesibles por internet.

`SQLite` no funciona con un modelo servidor/cliente. Se trata de construir bases de datos en un archivo local, sin poder conectarse de manera remota a las bases de datos.
La idea es tener un sistema ligero de manejo de bases de datos y aprovechar el uso del lenguaje `SQL` de manera local en un computador.

# Windows

## PostgreSQL y postgis

Para utilizar PostgreSQL en Windows, vamos a instalar los elementos siguientes:

* PostgreSQL, el sistema de gestión de base de datos
* Postgis la extensión espacial del sistema PostgreSQL

Para instalar esos elementos en Windows:

1. Descargar PostgreSQL desde la pagina: <https://www.enterprisedb.com/downloads/postgres-postgresql-downloads>. Les aconsejo instalar  la versión 16, si está disponible en su versión de Windows. Desde la versión 11, todas deberían ser suficientes para lo que vayamos a hacer en los talleres...
2. Instalarla siguiendo las instrucciones. El archivo de ejecución debería proponer los elementos siguientes:
  + PostgreSQL Server: Obligatorio
  + pgAdmin4: (facultativo) es un software para poder interactuar directamente con las bases de datos de PostgreSQL. Es una buena interfaz para PostgreSQL, vale la pena instalarlo si tienen el espacio suficiente
  + StackBuilder (obligatorio): nos va a permitir instalar postgis después
  + Command Line Tools: (facultativo) no estoy seguro que vayamos a utilizar esas herramientas en el curso, pero es relativamente ligero, y siempre es útil, les aconsejo instalarlo
3. Al final de la instalación de PostgreSQL, una nueva ventana va a abrirse con la ejecución de StackBuilder, seleccionar la base local. En "Spatial extensions" seleccionar Postgis y seguir con el proceso de instalación

## SQLite (no hay nada obligatorio que instalar!)

SQLite es un motor de gestión de base de datos muy ligero y muy practico.
No funciona en un modelo cliente/servidor, las bases de datos SQLite están contenidas en un archivo y se consultan directamente, de manera local.

La instalación de SQLite en Windows simplemente consiste en descargar unos archivos en un zip y ponerlos en el path de la maquina.
Este proceso es tan simple que el paquete R que permite interactuar con las bases de datos SQLite contiene un motor SQLite completo.
Para interactuar con las bases de datos SQLite y sus elementos espaciales en QGIS, no se necesita ninguna instalación tampoco, QGIS contiene de manera nativa todos los elementos utiles. 

Sin embargo, se puede instalar SQLite para interactuar con SQLite sin pasar por R, QGIS ni DBeaver. Si quieren hacerlo, la pagina <https://www.sqlite.org/index.html> contiene toda la documentación y los enlaces de descarga

## Interfaces para PostgreSQL y SQLite

Existen varios software para interactuar con las bases de datos en SQL.
Uno de los más fáciles es DBeaver.
Nos permitirá conectarnos y interactuar con las bases de datos en PostgreSQL y SQLite

Ir a <https://dbeaver.io/download/>, descargar y instalar DBeaver Community edition (versión actual: 24.2.5) para Windows.

# MacOS

## PostgreSQL

Vamos a necesitar PostgreSQL y postgis (su extensión espacial).

Parece que la aplicación [postgres.app](https://postgresapp.com/) contiene todo lo que necesitamos

Si quieren otras alternativas de instalación en MacOS, pueden referirse a la pagina : <https://www.postgresql.org/download/macosx/>

## SQLite

Parece que para instalar spatialite, la extensión espacial de SQLite la mejor solución es brew (<https://medium.com/@carusot42/installing-and-loading-spatialite-on-macos-28bf677f0436>).

Ahora bien, no les puedo asegurar que sea util instalarla... En Windows me dí cuenta que no era muy útil porque los software que íbamos a utilizar como interfaz ya tenían encapsulado SQLite y spatiaLite, así que tal vez, lo más practico es que no lo instalen y que miremos si funciona juntos (de todas formas, no es pesado instalar esos programas si los necesitamos)

## Interfaces

Vamos a utilizar DBeaver, que es disponible como dmg en <https://dbeaver.io/download/>


# Linux Mint y ubuntu
## PostgreSQL, postgis, SQLite y spatialite

Para instalar todos los paquetes SQL que vamos a necesitar (eso es valido el 1 de noviembre de 2022):

```bash
sudo apt install postgresql postgresql-contrib postgis postgresql-14-postgis-3 sqlite3 libsqlite3-mod-spatialite -y
```

## Interfaces para SQL

Vamos a utilizar DBeaver.
Como para R, tenemos que instalar un repositorio particular para DBeaver:

```bash
curl -fsSL https://dbeaver.io/debs/dbeaver.gpg.key | sudo gpg --dearmor -o /etc/apt/trusted.gpg.d/dbeaver.gpg
echo "deb https://dbeaver.io/debs/dbeaver-ce /" | sudo tee /etc/apt/sources.list.d/dbeaver.list
sudo apt update
sudo apt install dbeaver-ce -y
```

Si quieren, pueden instalar una interfaz especifica para PostgreSQL (ver <https://www.pgadmin.org/>):

```bash
sudo apt install pgAdmin4
```


